### ISSUE TITLE
new font awesome issue

### ISSUE THREAD

**Issue by helionmelion** [andrea-rosa/conky-config#1]
Is the new version of font awesome working with your conky? seems tricky to reference it

**Comment by andrea-rosa** [comment]
Some characters of version 5.0 of font awesome seem to work correctly for me, like [this](https://fontawesome.com/icons/american-sign-language-interpreting?style=solid):
![conky](https://user-images.githubusercontent.com/5749907/34486072-35ebbb26-efce-11e7-9cfe-b8a747303e7c.png)

Which one do you have tried?

**Comment by helionmelion** [comment]
I'm trying to reference font awesome in my own conky config but without sucess. Doing a google search I found your conky work, a very new one if comparing with years old configs found over there. Seems using ${font FontAwesome} is not sufficient. For instance, doing a `fc-list | grep -i awesome` returns: 

> /usr/share/fonts/TTF/fa-regular-400.ttf: Font Awesome 5 Free:style=Regular
/usr/share/fonts/TTF/fa-solid-900.ttf: Font Awesome 5 Free:style=Solid
/usr/share/fonts/TTF/fa-brands-400.ttf: Font Awesome 5 Brands:style=Regular

Im gonna try a workaround later, thanks for your response.

**Comment by JohnyProkie** [comment]
Sorry for reviving necro, but this issue is still opened.
According to this [post](https://ubuntuforums.org/showthread.php?t=2399795&p=13796336#post13796336) you need to install FontAwesome from repo and restart conky. Works for me on Ubuntu 18.04
Simply download font awesome from official site and install does not work.
so on Linux distro with Ubuntu PPAs you need to perform
`sudo apt install fonts-font-awesome`

**Comment by andrea-rosa** [comment]
> 
> 
> Sorry for reviving necro, but this issue is still opened.
> According to this [post](https://ubuntuforums.org/showthread.php?t=2399795&p=13796336#post13796336) you need to install FontAwesome from repo and restart conky. Works for me on Ubuntu 18.04
> Simply download font awesome from official site and install does not work.
> so on Linux distro with Ubuntu PPAs you need to perform
> `sudo apt install fonts-font-awesome`

Thanks Johny!
