### ISSUE TITLE
Question: how did you get the number of atoms of each element so small in your config?

### ISSUE THREAD

**Issue by fusion809** [andrea-rosa/conky-config#2]
Hi,

Your configs appeal to my eye too, albeit with a few tweaks, one tweak is I'd like to switch your caffeine formula with one for cyclophosphamide, but to do that it'd be mighty handy to know how you got the numbers so small, as they do give the illusion of subscripts, which is desirable. 

Thanks for your time,
Brenton

**Comment by andrea-rosa** [comment]
Hi Brenton,
Numbers in caffeine formula are made using subscript unicode characters. You can copy & paste directly from the table of [wikipedia](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Superscripts_and_subscripts_block) or from here: C₇H₁₅Cl₂O₂N₂P

**Comment by fusion809** [comment]
Thank you for your help. I've got things workin' perfectly now.
