### ISSUE TITLE
Cannot reference font awesome icons in conky

### ISSUE THREAD

**Issue by isuzufan** [andrea-rosa/conky-config#3]
I'm sorry if this is not the proper place for this question, but I cannot find any help online. 

I'm trying to insert font awesome icons in conky.  I think I have referenced the font correctly as...${font Font Awesome 5 Free:style=Regular:pixelsize=14}.   But when it comes to putting the character that corresponds to the icon itself...what do I do?  How do I know which key on my keyboard corresponds to which font awesome icon?

**Comment by andrea-rosa** [comment]
I cannot make it work with FontAwesome 5, if I put some spaces inside `${font}` conky will crash. Anyways, you should use the __copy glyph__ button in FontAwesome page, like this:
![screenshot_2018-08-30 font awesome 5 american-sign-language-interpreting](https://user-images.githubusercontent.com/5749907/44875781-7a834180-ac9f-11e8-8451-253315194d3a.png)

**Comment by isuzufan** [comment]
Thank you very much, Andrea. That helped me a lot!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrea-rosa** [comment]
You are welcome.

**Comment by dixonge** [comment]
@isuzufan Your syntax worked for me.
@andrea-rosa Thanks for the glyph copy idea. The page is laid out differently now, but if you look around you can still find the link to copy. A *lot* of the new glyphs don't work though. :(
